---
apiVersion: v1
kind: Service
metadata:
  name: webtop
spec:
  type: NodePort
  ports:
  - name: access1
    port: 3000
    targetPort: 3000
    nodePort: 30000
  - name: access2
    port: 3001
    targetPort: 3001
    nodePort: 30001
  selector:
    app: webtop
