network_subnets_info:
- Name: VPC-External-Block-b
  VLAN_ID: "Routed"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "TRUE"
  DHCP_Range_Start: 200
  DHCP_Range_End: 220
- Name: mgmt-b
  VLAN_ID: "40"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "TRUE"
  DHCP_Range_Start: 220
  DHCP_Range_End: 239
- Name: vsan-mgmt-b
  VLAN_ID: "41"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: storage-mgmt-b
  VLAN_ID: "42"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: vmotion-mgmt-b
  VLAN_ID: "43"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: htep-b
  VLAN_ID: "44"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "TRUE"
  DHCP_Range_Start: 130
  DHCP_Range_End: 200
- Name: vsan-wld-b
  VLAN_ID: "45"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: storage-wld-b
  VLAN_ID: "46"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: vmotion-wld-b
  VLAN_ID: "47"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: etep-b
  VLAN_ID: "48"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: uplink01-b
  VLAN_ID: "49"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: uplink02-b
  VLAN_ID: "50"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: rtep-b
  VLAN_ID: "51"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: app-net01-b
  VLAN_ID: "52"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: vpc-net01-b
  VLAN_ID: "53"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: dtgw-configuration-b
  VLAN_ID: "54"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: user-network-01b
  VLAN_ID: "55"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: console-network-b
  VLAN_ID: "58"
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
  
service_ip_pools:
  vsan_ip_pool_start: 11
  vsan_ip_pool_end: 40
  nfs_ip_pool_start: 131
  nfs_ip_pool_end: 160
  iscsi_ip_pool_start: 161
  iscsi_ip_pool_end: 190
  vmotion_ip_pool_start: 11
  vmotion_ip_pool_end: 40
  vcf_automation_ip_pool_start: 71
  vcf_automation_ip_pool_end: 74
  ans_ip_pool_start: 165
  ans_ip_pool_end: 174
  vsp_ip_pool_start: 141
  vsp_ip_pool_end: 160

appliance_ip_pools:
- name: VPC_Private_Transit_Gateway_IP_Block_Mgmt
  ip_pool: 172.16.120.0/24
- name: VPC_Private_Transit_Gateway_IP_Block_Wld01
  ip_pool: 172.16.121.0/24
- name: VPC_Private_Transit_Gateway_IP_Block_Wld02
  ip_pool: 172.16.122.0/24
- name: Private_CIDR_Mgmt
  ip_pool: 172.16.220.0/24
- name: Private_CIDR_Wld01
  ip_pool: 172.16.221.0/24
- name: Private_CIDR_wld02
  ip_pool: 172.16.222.0/24
- name: Supervisor_CIDR
  ip_pool: 10.96.0.0/23
- name: VCFA_Internal_Cluster_CIDR
  ip_subnet: 198.18.0.0/15

bgp_config:
  Router_AS: 65005
  Edge_Mgmt_AS: 65006
  Edge_Wld_AS: 65007
  Edge_Wld02_AS: 65008
  BGP_Password: VMware123!

ip_hostname_mappings:
- Hostname: router-b
  IP_Prefix: 1
- Hostname: router
  IP_Prefix: 129
- Hostname: proxy-b
  IP_Prefix: 129
- Hostname: ntp-b
  IP_Prefix: 129
- Hostname: dns
  IP_Prefix: 129
- Hostname: console
  IP_Prefix: 130
- Hostname: stg-infra-01b
  IP_Prefix: 3
- Hostname: stg-mgmt-01b
  IP_Prefix: 200
- Hostname: stg-wld-01b
  IP_Prefix: 200
- Hostname: sddcmanager-b
  IP_Prefix: 5
- Hostname: nsx-mgmt-b
  IP_Prefix: 20
- Hostname: nsx-mgmt-01b
  IP_Prefix: 21
- Hostname: nsx-mgmt-02b
  IP_Prefix: 22
- Hostname: nsx-mgmt-03b
  IP_Prefix: 23
- Hostname: nsx-gm-01b
  IP_Prefix: 37
- Hostname: edge-mgmt-01b
  IP_Prefix: 180
- Hostname: edge-mgmt-02b
  IP_Prefix: 181
- Hostname: vna-mgmt-01b
  IP_Prefix: 178
- Hostname: vna-mgmt-02b
  IP_Prefix: 179
- Hostname: vc-mgmt-b
  IP_Prefix: 10
- Hostname: vc-wld01-b
  IP_Prefix: 11
- Hostname: nsx-wld01-b
  IP_Prefix: 24
- Hostname: nsx-wld01-01b
  IP_Prefix: 25
- Hostname: nsx-wld01-02b
  IP_Prefix: 26
- Hostname: nsx-wld01-03b
  IP_Prefix: 27
- Hostname: edge-wld01-01b
  IP_Prefix: 182
- Hostname: edge-wld01-02b
  IP_Prefix: 183
- Hostname: vna-wld01-01b
  IP_Prefix: 194
- Hostname: vna-wld01-02b
  IP_Prefix: 195
- Hostname: vc-wld02-b
  IP_Prefix: 12
- Hostname: nsx-wld02-b
  IP_Prefix: 75
- Hostname: nsx-wld02-01b
  IP_Prefix: 76
- Hostname: nsx-wld02-02b
  IP_Prefix: 77
- Hostname: nsx-wld02-03b
  IP_Prefix: 78
- Hostname: edge-wld02-01b
  IP_Prefix: 184
- Hostname: edge-wld02-02b
  IP_Prefix: 185
- Hostname: vna-wld02-01b
  IP_Prefix: 196
- Hostname: vna-wld02-02b
  IP_Prefix: 197
- Hostname: nsx-shared-b
  IP_Prefix: 80
- Hostname: nsx-shared-01b
  IP_Prefix: 81
- Hostname: nsx-shared-02b
  IP_Prefix: 82
- Hostname: nsx-shared-03b
  IP_Prefix: 83
- Hostname: edge-shared-01b
  IP_Prefix: 186
- Hostname: edge-shared-02b
  IP_Prefix: 187
- Hostname: vna-shared-01b
  IP_Prefix: 198
- Hostname: vna-shared-02b
  IP_Prefix: 199
- Hostname: auto-platform-b
  IP_Prefix: 69
- Hostname: auto-b
  IP_Prefix: 70
- Hostname: o11n-01b
  IP_Prefix: 28
- Hostname: o11n-02b
  IP_Prefix: 29
- Hostname: ops-b
  IP_Prefix: 30
- Hostname: ops-01b
  IP_Prefix: 31
- Hostname: ops-02b
  IP_Prefix: 32
- Hostname: opsdata-01b
  IP_Prefix: 34
- Hostname: opsproxy-01b
  IP_Prefix: 35
- Hostname: opslcm-b
  IP_Prefix: 36
- Hostname: opsmgmt-b
  IP_Prefix: 40
- Hostname: opscollector-01b
  IP_Prefix: 41
- Hostname: opslogs-b
  IP_Prefix: 45
- Hostname: opslogs-01b
  IP_Prefix: 46
- Hostname: opslogs-02b
  IP_Prefix: 47
- Hostname: opslogs-03b
  IP_Prefix: 48
- Hostname: vcfinstaller-b
  IP_Prefix: 251
- Hostname: vidm-b
  IP_Prefix: 50
- Hostname: vidm-01b
  IP_Prefix: 51
- Hostname: vidb-01b
  IP_Prefix: 55
- Hostname: vidb-02b
  IP_Prefix: 56
- Hostname: vidb-03b
  IP_Prefix: 57
- Hostname: opsnet-b
  IP_Prefix: 60
- Hostname: opsnet-01b
  IP_Prefix: 61
- Hostname: opsnetcollector-01b
  IP_Prefix: 62
- Hostname: supervisor-mgmt-b
  IP_Prefix: 85
- Hostname: sup-mgmt-01b
  IP_Prefix: 86
- Hostname: sup-mgmt-02b
  IP_Prefix: 87
- Hostname: sup-mgmt-03b
  IP_Prefix: 88
- Hostname: SUP-upgrade-IP-mgmt-b
  IP_Prefix: 89
- Hostname: alb-b
  IP_Prefix: 90
- Hostname: alb-01b
  IP_Prefix: 91
- Hostname: alb-02b
  IP_Prefix: 92
- Hostname: alb-03b
  IP_Prefix: 93
- Hostname: albse-01b
  IP_Prefix: 94
- Hostname: albse-02b
  IP_Prefix: 95
- Hostname: albse-03b
  IP_Prefix: 96
- Hostname: dsm-01b
  IP_Prefix: 97
- Hostname: vlr-mgmt-b
  IP_Prefix: 98
- Hostname: vlr-wld01-b
  IP_Prefix: 99
- Hostname: vlr-wld02-b
  IP_Prefix: 100
- Hostname: hcx-mgmt-01b
  IP_Prefix: 63
- Hostname: hcx-ix-01b
  IP_Prefix: 64
- Hostname: hcx-ix-02b
  IP_Prefix: 65
- Hostname: hcx-ne-01b
  IP_Prefix: 66
- Hostname: hcx-ne-02b
  IP_Prefix: 67
- Hostname: hcx-wo-01-b
  IP_Prefix: 68
- Hostname: ssp
  IP_Prefix: 161
- Hostname: ssp-m
  IP_Prefix: 162
- Hostname: ssp-i
  IP_Prefix: 163
- Hostname: vmflowgen
  IP_Prefix: 164
- Hostname: basecli-1b		
  IP_Prefix: 210
- Hostname: basegui-1b		
  IP_Prefix: 211
- Hostname: basecli-2b
  IP_Prefix: 170
- Hostname: basegui-2b
  IP_Prefix: 171
- Hostname: esx-01b
  IP_Prefix: 101
- Hostname: esx-02b
  IP_Prefix: 102
- Hostname: esx-03b
  IP_Prefix: 103
- Hostname: esx-04b
  IP_Prefix: 104
- Hostname: esx-05b
  IP_Prefix: 105
- Hostname: esx-06b
  IP_Prefix: 106
- Hostname: esx-07b
  IP_Prefix: 107
- Hostname: esx-08b
  IP_Prefix: 108
- Hostname: esx-09b
  IP_Prefix: 109
- Hostname: esx-10b
  IP_Prefix: 110
- Hostname: esx-11b
  IP_Prefix: 111
- Hostname: esx-12b
  IP_Prefix: 112
- Hostname: esx-13b
  IP_Prefix: 113
- Hostname: esx-14b
  IP_Prefix: 114
- Hostname: esx-15b
  IP_Prefix: 115
- Hostname: esx-16b
  IP_Prefix: 116
- Hostname: esx-17b
  IP_Prefix: 117
- Hostname: esx-18b
  IP_Prefix: 118
- Hostname: esx-19b
  IP_Prefix: 119
- Hostname: esx-20b
  IP_Prefix: 120
- Hostname: esx-21b
  IP_Prefix: 121
- Hostname: esx-22b
  IP_Prefix: 122
- Hostname: esx-23b
  IP_Prefix: 123
- Hostname: esx-24b
  IP_Prefix: 124
- Hostname: esx-25b
  IP_Prefix: 125
- Hostname: esx-26b
  IP_Prefix: 126
- Hostname: esx-27b
  IP_Prefix: 127
- Hostname: esx-28b
  IP_Prefix: 128
- Hostname: esx-29b
  IP_Prefix: 129
- Hostname: esx-30b
  IP_Prefix: 130
- Hostname: vsan-fs-01b
  IP_Prefix: 131
- Hostname: vsan-fs-02b
  IP_Prefix: 132
- Hostname: vsan-fs-03b
  IP_Prefix: 133
- Hostname: vsan-fs-04b
  IP_Prefix: 134
- Hostname: vsan-fs-05b
  IP_Prefix: 135
- Hostname: vsan-fs-06b
  IP_Prefix: 136
- Hostname: vsan-fs-07b
  IP_Prefix: 137
- Hostname: vsan-fs-08b
  IP_Prefix: 138
- Hostname: vsan-fs-09b
  IP_Prefix: 139
- Hostname: vsan-fs-10b
  IP_Prefix: 140
- Hostname: vsan-fs-11b
  IP_Prefix: 141
- Hostname: vsan-fs-12b
  IP_Prefix: 142
- Hostname: vsan-fs-13b
  IP_Prefix: 143
- Hostname: vsan-fs-14b
  IP_Prefix: 144
- Hostname: vsan-fs-15b
  IP_Prefix: 145
- Hostname: vsan-fs-16b
  IP_Prefix: 146
- Hostname: vsan-fs-17b
  IP_Prefix: 147
- Hostname: vsan-fs-18b
  IP_Prefix: 148
- Hostname: vsan-fs-19b
  IP_Prefix: 149
- Hostname: vsan-fs-20b
  IP_Prefix: 150
- Hostname: vsan-fs-21b
  IP_Prefix: 151
- Hostname: vsan-fs-22b
  IP_Prefix: 152
- Hostname: vsan-fs-23b
  IP_Prefix: 153
- Hostname: vsan-fs-24b
  IP_Prefix: 154
- Hostname: vsan-fs-25b
  IP_Prefix: 155
- Hostname: vsan-fs-26b
  IP_Prefix: 156
- Hostname: vsan-fs-27b
  IP_Prefix: 157
- Hostname: vsan-fs-28b
  IP_Prefix: 158
- Hostname: vsan-fs-29b
  IP_Prefix: 159
- Hostname: vsan-fs-30b
  IP_Prefix: 160
- Hostname: edge-tep01-mgmt-01b
  IP_Prefix: 130
- Hostname: edge-tep02-mgmt-01b
  IP_Prefix: 131
- Hostname: edge-tep01-mgmt-02b
  IP_Prefix: 132
- Hostname: edge-tep02-mgmt-02b
  IP_Prefix: 133
- Hostname: edge-tep01-wld01-01b
  IP_Prefix: 134
- Hostname: edge-tep02-wld01-01b
  IP_Prefix: 135
- Hostname: edge-tep01-wld01-02b
  IP_Prefix: 136
- Hostname: edge-tep02-wld01-02b
  IP_Prefix: 137
- Hostname: edge-tep01-wld02-01b
  IP_Prefix: 138
- Hostname: edge-tep02-wld02-01b
  IP_Prefix: 139
- Hostname: edge-tep01-wld02-02b
  IP_Prefix: 140
- Hostname: edge-tep02-wld02-02b
  IP_Prefix: 141
- Hostname: edge-tep01-shared-01b
  IP_Prefix: 142
- Hostname: edge-tep02-shared-01b
  IP_Prefix: 143
- Hostname: edge-tep01-shared-02b
  IP_Prefix: 144
- Hostname: edge-tep02-shared-02b
  IP_Prefix: 145
- Hostname: edge-uplink01-mgmt-01b
  IP_Prefix: 2
- Hostname: edge-uplink01-mgmt-02b
  IP_Prefix: 3
- Hostname: edge-uplink02-mgmt-01b
  IP_Prefix: 130
- Hostname: edge-uplink02-mgmt-02b
  IP_Prefix: 131
- Hostname: edge-uplink01-wld01-01b
  IP_Prefix: 6
- Hostname: edge-uplink01-wld01-02b
  IP_Prefix: 7
- Hostname: edge-uplink02-wld01-01b
  IP_Prefix: 134
- Hostname: edge-uplink02-wld01-02b
  IP_Prefix: 135
- Hostname: edge-uplink01-wld02-01b
  IP_Prefix: 10
- Hostname: edge-uplink01-wld02-02b
  IP_Prefix: 11
- Hostname: edge-uplink02-wld02-01b
  IP_Prefix: 138
- Hostname: edge-uplink02-wld02-02b
  IP_Prefix: 139
- Hostname: edge-uplink01-shared-01b
  IP_Prefix: 14
- Hostname: edge-uplink01-shared-02b
  IP_Prefix: 15
- Hostname: edge-uplink02-shared-01b
  IP_Prefix: 142
- Hostname: edge-uplink02-shared-02b
  IP_Prefix: 143
- Hostname: supervisor-wld-b
  IP_Prefix: 188
- Hostname: sup-wld-01b
  IP_Prefix: 189
- Hostname: sup-wld-02b
  IP_Prefix: 190
- Hostname: sup-wld-03b
  IP_Prefix: 191
- Hostname: SUP-upgrade-IP-wld-b
  IP_Prefix: 192
- Hostname: salt-b
  IP_Prefix: 193
- Hostname: vsp-01b
  IP_Prefix: 131
- Hostname: shared-01b
  IP_Prefix: 132
- Hostname: license-b
  IP_Prefix: 133
- Hostname: esx-04a
  IP_Prefix: 204
- Hostname: esx-05a
  IP_Prefix: 205
- Hostname: esx-06a
  IP_Prefix: 206
- Hostname: esx-07a
  IP_Prefix: 207
- Hostname: esx-08a
  IP_Prefix: 208

overlay_networks_info: 
- Name: cloud-net-b
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: seg-dev-b
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "TRUE"
  DHCP_Range_Start: 100
  DHCP_Range_End: 120
- Name: seg-qa-b
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "TRUE"
  DHCP_Range_Start: 230
  DHCP_Range_End: 250
- Name: seg-prod-b
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "TRUE"
  DHCP_Range_Start: 100
  DHCP_Range_End: 120
- Name: seg-web-b
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "TRUE"
  DHCP_Range_Start: 230
  DHCP_Range_End: 250
- Name: seg-db-b
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "TRUE"
  DHCP_Range_Start: 100
  DHCP_Range_End: 120
- Name: seg-app-b
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "TRUE"
  DHCP_Range_Start: 230
  DHCP_Range_End: 250
- Name: container-ingress-b
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
- Name: container-egress-b
  Subnet: ""
  SubnetMask: ""
  Gateway: ""
  DHCP: "FALSE"
  DHCP_Range_Start: ""
  DHCP_Range_End: ""
