tinker panic 0
restrict default nomodify notrap nopeer noquery
restrict 127.0.0.1
restrict -6 ::1
driftfile /var/lib/ntp/drift/ntp.drift
logfile /var/log/ntp.log
server 127.127.1.0
fudge 127.127.1.0 stratum 10
